# Generated by Django 5.0.6 on 2024-06-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
